### ISSUE TITLE
Changing mega menu order for Business

### ISSUE THREAD

**Issue by anniecrombie** [neoinsight/start-business#2]
We are planning to change the mega menu order under the Business menu to the following. It would be great if we could reflect this order in the prototype. 

Starting a business
Business grants and financing
Business taxes
Hire and manage employees
International trade and investment
Permits, licences and regulations
Sell to government
Research and development (R&D) and innovation
Research and business intelligence
Intellectual property and copyright
Maintain, grow and improve your business
Protect your business
Bankruptcy for business

If anyone can help with that, that would be great. Thanks!

**Comment by neoinsight** [comment]
I think @patlaj has been fiddling with the menu bits and should be able to do this. Right @patlaj?

**Comment by patlaj** [comment]
I should be able to, if github is kind to me today. ;)

**Comment by anniecrombie** [comment]
Thanks @patlaj. No rush. Just wanted to note it before I forget.

**Comment by patlaj** [comment]
No problem, I need practice anyway so I can make sure I'm doing things correctly. Or at least breaking as little as possible. ;)

It's done now, but because of the browser cache you'll probably need to load the menu file separately and force-refresh before it'll show up properly in the megamenu:

https://neoinsight.github.io/start-business/ajax/sitemenu2-en.html
